## Example :1

In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = {
    "City" : ["Delhi","Mumbai","Banglore","Delhi","Mumbai"]
}
df = pd.DataFrame(data) 
print(df)

       City
0     Delhi
1    Mumbai
2  Banglore
3     Delhi
4    Mumbai

In [3]:
encoded = pd.get_dummies(df["City"]).astype(int)

print(encoded)

   Banglore  Delhi  Mumbai
0         0      1       0
1         0      0       1
2         1      0       0
3         0      1       0
4         0      0       1

## Example : 2

In [10]:
data =pd.DataFrame ({
    "Education" : ["master","degree","diploma","master","degree"] , 
    "Department" : ["IT","HR","Finance","IT","HR"] , 
    "City" : ["Delhi","Mumbai","Delhi","Bengalore","Mumbai"] 

 })
print(data)

  Education Department       City
0    master         IT      Delhi
1    degree         HR     Mumbai
2   diploma    Finance      Delhi
3    master         IT  Bengalore
4    degree         HR     Mumbai

In [11]:
pd.get_dummies(data,dtype=int)

,Education_degree,Education_diploma,Education_master,Department_Finance,Department_HR,Department_IT,City_Bengalore,City_Delhi,City_Mumbai
0,0,0,1,0,0,1,0,1,0
1,1,0,0,0,1,0,0,0,1
2,0,1,0,1,0,0,0,1,0
3,0,0,1,0,0,1,1,0,0
4,1,0,0,0,1,0,0,0,1

In [4]:
from sklearn.preprocessing import OneHotEncoder 
import pandas as pd 

df = pd.DataFrame ( {
    "city" : ["Delhi","Mumbai","Banglore","Delhi","Mumbai"]
}) 

end = OneHotEncoder() 
encoded = end.fit_transform(df[["city"]]) 

print(encoded.toarray())

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [8]:
from sklearn.preprocessing import OneHotEncoder 
import pandas as pd 

data =pd.DataFrame ({
    "Education" : ["master","degree","diploma","master","degree"] , 
    "Department" : ["IT","HR","Finance","IT","HR"] , 
    "City" : ["Delhi","Mumbai","Delhi","Bengalore","Mumbai"] 

 }) 

encoder = OneHotEncoder()
after = encoder.fit_transform(data[["Education","Department", "City"]]) 

print(after.toarray())

[[0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1.]]

In [11]:
pd.get_dummies(data,drop_first= True)

,Education_diploma,Education_master,Department_HR,Department_IT,City_Delhi,City_Mumbai
0,False,True,False,True,True,False
1,False,False,True,False,False,True
2,True,False,False,False,True,False
3,False,True,False,True,False,False
4,False,False,True,False,False,True

In [25]:
import pandas as pd 

df = pd.DataFrame({
    "colors" : ["Red","Blue","Green","Red"] 
    
}) 

pd.get_dummies(df,dtype=int)

   colors_Blue  colors_Green  colors_Red
0            0             0           1
1            1             0           0
2            0             1           0
3            0             0           1

## Label Encoding

In [2]:
from sklearn.preprocessing import LabelEncoder 
import pandas as pd 

data = pd.DataFrame({
    "Size" : ["Small","medium","Large"]
})

encoder = LabelEncoder()
size_encoded = encoder.fit_transform(data["Size"]) 

print(data)

     Size
0   Small
1  medium
2   Large

## Target encoding

In [4]:
import pandas as pd 

data = pd.DataFrame ({
    "City" : ["Delhi","Mumbai","Delhi","Mumbai"], 
    "Price" : [500000,800000,550000,850000]
})

encoded = data.groupby("City")["Price"].mean() 
data["city_encoded"] = data["City"].map(encoded) 
print(data)

     City   Price  city_encoded
0   Delhi  500000      525000.0
1  Mumbai  800000      825000.0
2   Delhi  550000      525000.0
3  Mumbai  850000      825000.0

In [6]:
import pandas as pd 
data = pd.read_csv("Titanic_train.csv") 
encoded = pd.get_dummies(data,columns=["Sex"],dtype=int)
print(encoded.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris  22.0      1      0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0
2                             Heikkinen, Miss. Laina  26.0      0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0
4                           Allen, Mr. William Henry  35.0      0      0

             Ticket     Fare Cabin Embarked  Sex_female  Sex_male
0         A/5 21171   7.2500   NaN        S           0         1
1          PC 17599  71.2833   C85        C           1         0
2  STON/O2. 3101282   7.9250   NaN        S           1         0
3            113803  53.1000  C123        S           1         0
4            373450   8.0500   NaN        S           0         1

In [7]:
import pandas as pd 
df = pd.read_csv("homeprices.csv") 
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [16]:
dummies = pd.get_dummies(df.town).astype(int) 
dummies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [18]:
merged = pd.concat([df,dummies],axis = 'columns')
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [19]:
final = merged.drop(['town'],axis = 'columns') 
final

    area   price  monroe township  robinsville  west windsor
0   2600  550000                1            0             0
1   3000  565000                1            0             0
2   3200  610000                1            0             0
3   3600  680000                1            0             0
4   4000  725000                1            0             0
5   2600  585000                0            0             1
6   2800  615000                0            0             1
7   3300  650000                0            0             1
8   3600  710000                0            0             1
9   2600  575000                0            1             0
10  2900  600000                0            1             0
11  3100  620000                0            1             0
12  3600  695000                0            1             0

In [20]:
final = final.drop(['west windsor'],axis = 'columns')
final

    area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [21]:
X = final.drop('price', axis='columns')
X

    area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1